spring:
  application:
    name: assistant
  profiles:
    active: openai

country:
  api:
    base-url: ${COUNTRY_API_BASE_URL:https://restcountries.com/v3.1}
    country-by-name-path: ${COUNTRY_API_PATH:/name/{name}?fullText=true}

ollama:
  base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
  embedding-model-name: ${OLLAMA_EMBEDDING_MODEL:nomic-embed-text}
  timeout: ${OLLAMA_TIMEOUT:1000}

pgvector:
  host: ${PGVECTOR_HOST:localhost}
  port: ${PGVECTOR_PORT:5432}
  database: ${DB_NAME:assistant_db}
  user: ${DB_USER:postgres}
  password: ${DB_PASSWORD:postgres}
  dimension: ${PGVECTOR_DIMENSION:768}
  table: ${PGVECTOR_TABLE:embeddings}

rag:
  knowledge-base-dir: ${RAG_KNOWLEDGE_BASE_DIR:cdq-knowledge-base}
  file-glob: ${RAG_FILE_GLOB:*.*}
  chunk-size: ${RAG_CHUNK_SIZE:1000}
  chunk-overlap: ${RAG_CHUNK_OVERLAP:100}
  max-results: ${RAG_MAX_RESULTS:2}
  min-score: ${RAG_MIN_SCORE:0.5}