spring:
  application:
    name: assistant
  profiles:
    active: ollama

country:
  api:
    base-url: ${COUNTRY_API_BASE_URL:https://restcountries.com/v3.1}
    country-by-name-path: ${COUNTRY_API_PATH:/name/{name}?fullText=true}